name: Generate Snake

on:
  schedule: # ejecuta automáticamente
    - cron: "0 0 * * *"  # todos los días a medianoche UTC
  workflow_dispatch: # permite lanzarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: PatriciaAlEs
          outputs: dist/snake.svg

      - name: Push to output branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "Generate snake animation"
          add: "dist/snake.svg"
